language: node_js
node_js:
  - '10.15.0'

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
      sudo: required
      dist: trusty
      services: docker

env:
  global:
    - LND_TAG=cfb5e249b9d6dae9e44dcf56c29c3eda531290fe
    - BTCD_TAG=306aecffea325e97f513b3ff0cf7895a5310651d
    - GO_TAG=1.11.4
    - GOROOT=$HOME/go
    - GOPATH=$HOME/gocode
    - PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    - NAP_TIME=20000
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - ./assets/script/install_lnd.sh

script:
  - npm test
  - npm run build-storybook

deploy:
  provider: script
  script: ./assets/script/build_app.sh
  skip_cleanup: true
  on:
    repo: lightninglabs/lightning-app
    tags: true

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine